### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: META-INF/LICENSE

### ISSUE THREAD

**Issue by chaokunyang** [mdedetrich/sbt-apache-sonatype#45]
I used [sbt-apache-sonatype](https://github.com/mdedetrich/sbt-apache-sonatype) to publish apache fury scala jar to nexus with command `sbt clean +publishSigned`, but it failed with:
![image](https://github.com/user-attachments/assets/7b31846e-2dfc-485e-9a63-ea3e857deaa3)

```java
[error] java.util.zip.ZipException: duplicate entry: META-INF/LICENSE
[error] 	at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:259)
[error] 	at java.base/java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:115)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:717)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6(IO.scala:726)
[error] 	at sbt.io.IO$.$anonfun$writeZip$6$adapted(IO.scala:726)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at sbt.io.IO$.writeZip(IO.scala:726)
[error] 	at sbt.io.IO$.$anonfun$archive$2(IO.scala:676)
[error] 	at sbt.io.IO$.$anonfun$archive$2$adapted(IO.scala:673)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:773)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:753)
[error] 	at sbt.io.Using.apply(Using.scala:28)
[error] 	at sbt.io.IO$.withZipOutput(IO.scala:753)
[error] 	at sbt.io.IO$.archive(IO.scala:673)
[error] 	at sbt.io.IO$.jar(IO.scala:638)
[error] 	at sbt.Package$.makeJar(Package.scala:229)
[error] 	at sbt.Package$.$anonfun$apply$4(Package.scala:152)
[error] 	at sbt.Package$.$anonfun$apply$4$adapted(Package.scala:150)
[error] 	at sbt.util.Tracked$.$anonfun$outputChangedW$1(Tracked.scala:129)
[error] 	at sbt.Package$.apply(Package.scala:162)
[error] 	at sbt.Defaults$.$anonfun$packageTask$1(Defaults.scala:1918)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (Compile / packageSrc) java.util.zip.ZipException: duplicate entry: META-INF/LICENSE
[error] Total time: 6 s, completed Sep 26, 2024, 9:56:47 PM
```

My sbt version 1.10.2, jdk version is jdk21. sbt config is in https://github.com/apache/fury/pull/1729

**Comment by pjfanning** [comment]
@chaokunyang see https://github.com/apache/fury/pull/1859 and #39
